services:
  db:
    image: base
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.18.1
    environment:
      DATA_SOURCE_URI: "db:5432/${POSTGRES_DB}?ssl_mode=disable"
      DATA_SOURCE_USER: "${POSTGRES_USER}"
      DATA_SOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
  k6:
    image: grafana/k6:1.5.0
