services:
  postgres:
    image: postgres:18.1-alpine3.23
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.18.1
    environment:
      DATA_SOURCE_URI: postgres:5432/postgres?sslmode=disable
      DATA_SOURCE_USER: ${POSTGRES_USER}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/custom.ini:/usr/share/grafana/conf/custom.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
  k6:
    build:
      context: ./k6
      dockerfile: Dockerfile
    volumes:
      - ../k6:/app

volumes:
  grafana-storage: {}
