services:
  db:
    image: postgres:18.1-alpine3.23
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.18.1
    environment:
      DATA_SOURCE_URI: "127.0.0.1:5432/${POSTGRES_DB}?ssl_mode=disable"
      DATA_SOURCE_USER: "${POSTGRES_USER}"
      DATA_SOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/custom.ini:/usr/share/grafana/conf/custom.ini:ro
      - ./grafana/provisioning:/etc/grafana/provisioning
  k6:
    image: grafana/k6:1.5.0
